### ISSUE TITLE
missing gridlines: InterruptedGoodeHomolosine

### ISSUE THREAD

**Issue by mathause** [SciTools/cartopy#1015]
I just noticed that the only one x-gridline gets drawn with InterruptedGoodeHomolosine. This is is in contrast to the [Example](http://scitools.org.uk/cartopy/docs/v0.15/crs/projections.html#interruptedgoodehomolosine). So maybe it's a matplotlib issue?

    import cartopy
    import matplotlib
    print(cartopy.__version__)
    print(matplotlib.__version__)
0.15.1
2.1.1

    import cartopy.crs as ccrs
    import matplotlib.pyplot as plt

    ax = plt.axes(projection=ccrs.InterruptedGoodeHomolosine())
    ax.coastlines(resolution='110m')
    ax.gridlines()

![interruptedgoodehomolosine_gridlines](https://user-images.githubusercontent.com/10194086/35558846-602e5696-05a9-11e8-8335-f8247d7d3a7c.png)

[Expected outcome](http://scitools.org.uk/cartopy/docs/v0.15/crs/projections.html#interruptedgoodehomolosine)

**Comment by pelson** [comment]
Yes, it looks likely that this is a matplotlib version issue. @QuLogic - did you see anything like this on your mpl 2 travels?

**Comment by QuLogic** [comment]
It seems to come from matplotlib/matplotlib@9982e400c7b21afdebe364d8eb1a8565c5383242, but I'm not entirely sure why.

**Comment by QuLogic** [comment]
Though 6061b2c3a711cf7e706ca3b37103bf7c4c52f2b6 should have been a related fix; not sure why it didn't help.

**Comment by QuLogic** [comment]
Well, this was a confusing one. It turns out that the locations of the meridians are fine, but what changed were the parallels. The meridians are drawn from the minimum parallel to the maximum parallel. In Matplotlib 1.5.3, the parallels were `range(-80, 81, 20)`, but with 2.0.0, the parallels are `range(-90, 91, 18)`. Technically, this was always sort of a bug in Matplotlib locators, since the limits are actually [-78.4, 78.4] and the outer values should not be drawn.

_Apparently_, for IGH, if you draw the meridians from -90 to 90 latitude, they don't transform right. If I patch it to start at -89, then all the gridlines show up again.

So there are two bugs:
1. We need to clip gridlines to the actual view limits; this is something Matplotlib does even though locators output values outside the specified limits.
2. Something may or may not be weird with IGH at -90

**Comment by QuLogic** [comment]
Of course, the former is easier said than done, since sometimes you _want_ the gridline to end at the last of the other direction, and sometimes you don't, depending on the projection. This might need some kind of option to get right.
