### ISSUE TITLE
Cannot change the border width of the cartopy axes

### ISSUE THREAD

**Issue by pmetx** [SciTools/cartopy#1077]
### Description

I just started to use cartopy.  I cannot change the (frame) border width of the cartopy axes by using mpl.rcParams['axes.linewidth']. But mpl.rcParams always works for other axes or basemap.

#### Code to reproduce
``` python
import cartopy as cpy
import cartopy.feature as cpf
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['axes.linewidth'] = 3

ax = plt.axes(projection=cpy.crs.PlateCarree())
ax.add_feature(cpf.LAND, facecolor='0.9', linewidth=0.5)
ax.add_feature(cpf.OCEAN, linewidth=0.5)
ax.coastlines(resolution='50m', linewidth=0.5)

plt.savefig('cpy.test.png', dpi=600, bbox_inches='tight')
```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### Operating system
Windows 10
Python 2.7.14

### Cartopy version
cartopy-0.16.0
shapely-1.6.4
owslib-0.16.0
pyepsg-0.3.2

Matplotlib 2.2.2

### conda list

```
```

### pip list

```
```

</details>

**Comment by pelson** [comment]
@pmetx - the fix here is to set the linewidth directly on ``ax.outline_patch``. Cartopy needs to improve its documentation around ``ax.patch`` (the standard matplotlib approach) and why cartopy doesn't use it (it has ``ax.background_patch`` and ``ax.outline_patch`` instead https://scitools.org.uk/cartopy/docs/latest/matplotlib/geoaxes.html#cartopy.mpl.geoaxes.GeoAxes.outline_patch).

I'm going to keep this open in order to track improvements to the documentation in this area.

**Comment by pmetx** [comment]
@pelson Thanks. 
I tried this method `ax.outline_patch.set_linewidth(0.5)` and it works.  I guess the document for ax.patch may be helpful if someone want to use other methods/properties of ax.outline_patch, right?
https://matplotlib.org/api/_as_gen/matplotlib.patches.Patch.html#matplotlib.patches.Patch

**Comment by pelson** [comment]
Yep, that's right.

Glad I could help. Will try to get some improvements to the docs over the weekend (it's scipy conference weekend, and hopefully I'll be sprinting with a bunch of folks on the docs 👍 )
