### ISSUE TITLE
Caching maps between plots

### ISSUE THREAD

**Issue by liz-hourahine** [SciTools/cartopy#1093]
We've created a function using matplotlib to make 1000 plots from netcdf files, and using cartopy to create a base map for each plot. However creating this base map is very expensive, and considering that we only need the same base map for each plot, I was wondering if there was any way to create the base map externally and call it back within the function, or cache the base map between iterations?

@jacobtomlinson suggests @pelson may have some thoughts...

Have realised this is a duplicate of issue #732 :)

**Comment by liz-hourahine** [comment]
Ah, I thought it was solved but it appears that the caching solution in issue #732 do not solve the issue of expensiveness at runtime. A way for the mapping to be done externally to the next stages of plotting would be fantastic.

**Comment by akrherz** [comment]
see matplotlib/basemap#354

**Comment by pelson** [comment]
Pickling is definitely a good option if you need to cache out-of-process. If you are talking about a small number of processes producing a large number of figures, you might have more luck with simply removing the matplotlib artists that you no longer require.

I don't think this is going to require any changes to cartopy, and I'd like to keep user questions in one place (StackOverflow), so would you mind if I ask you to ask on StackOverflow (with the cartopy tag). In the question, could I also get a little more information about the type of visualisation you are doing (maybe even a screenshot!) so that I can tailor the answer to your needs a bit more.

Please include the URL to the question on this issue for cross-referencing purposes.

Thanks!
