### ISSUE TITLE
Build wheels and upload to pypi

### ISSUE THREAD

**Issue by ngoldbaum** [SciTools/cartopy#1174]
Currently installing cartopy via pip is somewhat painful, e.g. #1035. This could be ameliorated if cartopy had wheels uploaded on pypi for stable releases.

I think adding the pyproject.toml file will separately mitigate #1035, however uploading wheels will allow many more users, who do not necessarily have compilers set up on their machine, to use cartopy without having to setup a build environment.

I've been pretty happy using https://github.com/matthew-brett/multibuild/ to automate building wheels for yt. I'd be happy to give advice about getting that setup for cartopy.

Note that this came up in the context of us adding catopy as an optional dependency of yt, see https://github.com/yt-project/yt/pull/1966.

**Comment by dopplershift** [comment]
We'd love to. The problem is that CartoPy depends on Shapely, which links to GEOS, and CartoPy directly links to GEOS.  (See #805) If the CartoPy wheels and the Shapely wheels are not linked to the same binary compatible version of GEOS, **BOOM**. (This is not a problem for conda/conda-forge.)

Until this is resolved somehow, providing brittle wheels seems worse than providing none at all.

**Comment by barronh** [comment]
I am curious if there is a way. Shapely Wheels are created using a docker script. Could a docker build have the same docker build as a prerequisite?

**Comment by greglucas** [comment]
wheels are now built and uploaded to PyPI as of v0.22
