### ISSUE TITLE
imshow with non-global data extent can hang

### ISSUE THREAD

**Issue by MatthewTurk** [SciTools/cartopy#1184]
In some situations, it seems it is possible to get cartopy to query the scipy kdtree for points that can't be found.  This seems to take place when the data covers a reasonably small subset of the globe, and the axes haven't been set up with an extent.  Setting an extent in advance of calling imshow can prevent this.  None of this seems to be an actual *bug* per se, but rather a combination of the user (me!) requesting odd things and then cartopy doing its best to provide them, and I wanted to report in case there's a simple way to ease the diagnostic process for others.

#### Code to reproduce

This code reproduces the hang:

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import numpy as np

data = np.random.random((256, 256))

ax = plt.axes(projection=ccrs.Mollweide())
extent = [-27.0, 27.0, -13.5, 13.5]
# ax.set_extent(extent)
ax.imshow(data, extent = extent, transform = ccrs.PlateCarree())

plt.savefig('example.png')
```

Uncommenting the `ax.set_extent` line (in advance of the call to `imshow`) eliminates the hang.

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### Operating system

`4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### Cartopy version

0.16.0

Scipy is 1.1.0, so it is using `balanced_tree=False`.

</details>

This is, admittedly, something of an odd corner case, considering that the workaround of setting the extent in advance will fix things.  Tracking it through the code, it seems that in `img_transform.py`, we end up with results that `target_xyz` has lots and lots of `inf` values, which hang the scipy kdtree query.

It seems that there may be an elegant solution (similar to where `np.isinf(distances)`) that involves masking out the inf values before the query, although I was not able to determine it.

**Comment by QuLogic** [comment]
It only takes about 30 seconds for me, so not quite a hang. That being said, with #1150, it only takes ~3 seconds. So with the next release and pykdtree installed, it will be much better.

**Comment by pelson** [comment]
> In some situations, it seems it is possible to get cartopy to query the scipy kdtree for points that can't be found. This seems to take place when the data covers a reasonably small subset of the globe, and the axes haven't been set up with an extent. 

To add more detail to what is going on, we project all image pixels out to geocentric coordinates (xyz) and build a KD-Tree in 3D space. We then query the 3D-Tree for any points that are required in order to rasterize the image in the new coordinate system (based on the current extents of the Axes). This is pretty heavy lifting for a KDTree, and it is fair to say that the performance was a secondary objective to the correctness. Thankfully there has been a lot of work put into the performance of the pykdtree implementation, and @QuLogic hooked us into that in #1150.

As @QuLogic says, on master with ``pykdtree`` installed (available through conda-forge) the example runs at a very pleasant performance. There is certainly potential to improve that further (particularly for re-draws and interactivity).
