### ISSUE TITLE
Dropping legacy python support

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#1186]
We are suffering from lots of small cuts by supporting Python 2 in cartopy. As far as I can tell, none of the developers reach for py2 over py3 and this means that we are always doubling-back to ensure compatibility.

Some of the things that we are really missing out on:

 * Calling ``super()`` without arguments (happened this morning in #1181)
 * Unicode literals and default unicode encoding of ``.py`` files (happened this morning in #1182) 
 * An expressive keyword only argument syntax (``def func(*, kw_only=blah)``) (happened yesterday in  handling kwarg API breakage vs consistent ordering of code: https://github.com/SciTools/cartopy/pull/1180/files#diff-6dfcada343269e6678a777c4f9a5223dR1757)
 * more...

The time has come to put to writing the date of a final release with python 2 support. Frankly, it isn't a sustainable model to claim that an older release will be the final "supported" python 2 release - once we make the decision, there should be no further maintenance of a py2 branch. Users can still install old versions, but as will other old releases, that would be under no expectation of maintenance / bug-fixes / support.

I'm not yet convinced that v0.17 is that release (happening this week), but I could very easily see it as the penultimate release with py2 support (thus making ``v0.18`` / ``v1.0`` the magic number). If that is what we want, it would be great to get that message out in the v0.17 release notes.

At the moment, this isn't a tangible proposal - I just want to start the ball rolling.

**Comment by dopplershift** [comment]
👍  to making 0.18 the last Python 2.7 release. I’d love to get that out the door (depending on the amount of fixes/features done) in the Spring/Summer 2019 timeframe.

**Comment by QuLogic** [comment]
I'm definitely happy to see this happen at some point, especially given Matplotlib already did so. I would guess we'd like to get the fancy gridline labelling in before making the split at least.

**Comment by hugovk** [comment]
Here's the pip installs for Cartopy from PyPI for last month, showing low numbers for Python 2:

| category | percent | downloads |
|----------|--------:|----------:|
|        3 |  78.67% |     4,832 |
|        2 |  16.53% |     1,015 |
| null     |   4.80% |       295 |
| Total    |         |     6,142 |


Source: `pypistats python_major --last-month cartopy`


| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  48.89% |     3,003 |
|      3.5 |  19.70% |     1,210 |
|      2.7 |  16.53% |     1,015 |
|      3.7 |   8.14% |       500 |
| null     |   4.80% |       295 |
|      3.4 |   1.82% |       112 |
|      3.3 |   0.11% |         7 |
| Total    |         |     6,142 |

Source: `pypistats python_minor --last-month cartopy`

**Comment by QuLogic** [comment]
That seemed high to me initially, but turns out it's better than Matplotlib, which is already Py3-only (though there's still a bugfix branch with Py2 support):

`pypistats python_major --last-month matplotlib`:

| category | percent | downloads |
|----------|--------:|----------:|
|        3 |  55.34% | 1,835,154 |
|        2 |  43.93% | 1,456,856 |
| null     |   0.73% |    24,256 |
| Total    |         | 3,316,266 |


`pypistats python_minor --last-month matplotlib`:

| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  43.91% | 1,456,264 |
|      3.6 |  35.55% | 1,179,014 |
|      3.5 |  10.19% |   338,008 |
|      3.7 |   6.82% |   226,297 |
|      3.4 |   2.76% |    91,504 |
| null     |   0.73% |    24,256 |
|      2.6 |   0.02% |       592 |
|      3.3 |   0.00% |       158 |
|      3.8 |   0.00% |       131 |
|      3.2 |   0.00% |        42 |
| Total    |         | 3,316,266 |

**Comment by hugovk** [comment]
Here's Matplotlib over time:

![image](https://user-images.githubusercontent.com/1324225/48664188-937fdf80-eaa3-11e8-978e-2eb77d98f9b4.png)

https://github.com/hugovk/pypi-tools

**Comment by dopplershift** [comment]
Matplotlib going 3.x only biases download numbers, since all downloads due to upgrades (not new setups) will be Python 3 only now.

**Comment by hugovk** [comment]
Please see PR #1237.

**Comment by pelson** [comment]
Another reason:
 * AttributeError: 'list' object has no attribute 'clear'

**Comment by hugovk** [comment]
Please see PR #1540.
