### ISSUE TITLE
some shape files cannot be read correctly 

### ISSUE THREAD

**Issue by flydream0428** [SciTools/cartopy#1217]
### Description

I am trying to add a few shape files to a Cartopy basemap. It turns out that some shape files work, while the others doesn't. I have googled for the whole day without any luck. Can you please help. Below is the code I am using. The two shape files can be downloaded here:
https://www.dropbox.com/sh/2lp93uz28rmyfcs/AAAiA-p4ge5KzHDC5dXlflXga?dl=0
I have posted this on StackOverflow here:
https://stackoverflow.com/questions/53167271/shape-files-do-not-show-on-a-cartopy-basemap/53181219#53181219
Someone points out that there may be an issue in the second shapefile. However, if I read this by pyshp, it works fine. Pyshp can read the shapes correctly. 

#### Code to reproduce

```
import matplotlib.pyplot as plt 
import cartopy.crs as ccrs
from cartopy.io.img_tiles import OSM
from cartopy.io import shapereader

#%% ======== map paramters =================
map_extent_eastings=(378000,390000)
map_extent_northings=(6427500,6443000)

#%%
plt.subplots(1,1,figsize=(10,10))
ax = plt.axes(projection=ccrs.epsg(28350))
ax.set_extent([map_extent_eastings[0],map_extent_eastings[1],map_extent_northings[0],map_extent_northings[1]],crs=ccrs.epsg(28350))

tiler = OSM() 
cur_CRS = tiler.crs
zoom = 8 #12 for the final 
ax.add_image(tiler, zoom, interpolation='bilinear' )


#============= Figure out why this deosn't work ===================
### this one doesn't work 
ax.add_geometries(shapereader.Reader('data/AdditionalPumping_south_v2_test.shp').geometries(), 
                  ccrs.epsg(28350),facecolor='none',edgecolor='r',linewidth=1.5,zorder=10)

# This one works 
ax.add_geometries(shapereader.Reader('data/MAR_locations_v2.shp').geometries(), 
                  ccrs.epsg(28350),facecolor='none',edgecolor='r',linewidth=1.5,zorder=10)

plt.show()
```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
I was able to load and plot the files in Cartopy with the Fiona library installed, if you have the option to install that it will resolve your issue. I have also created a pull request to update the basic shapereader to use shapely to create the geometries, rather than within Cartopy, which may be causing the issues here. See #1210 if you want to give it a shot with your geometries.

**Comment by flydream0428** [comment]
Thanks heaps, I tried this. It solved my problem. Thanks again!

**Comment by pelson** [comment]
Thanks for pointing to the Fiona solution @greglucas! Good to have it! 😉 
@flydream0428 - when providing a bug report, if possible try to include the full version list of your environment - I would hope this issue is solved by using a newer version of pyshp, but I don't know what version you had. It may be that we need to raise this with the project so that the bug can be fixed upstream.

Thanks,
