### ISSUE TITLE
How to plot data with partially missing coordinate arrays?

### ISSUE THREAD

**Issue by lvankampenhout** [SciTools/cartopy#1254]
### Description
I'm attempting to plot [CLARA-A2 satellite data](https://www.atmos-chem-phys.net/17/5809/2017/) over Greenland. This data has its coordinate arrays (latitude / longitude) partially missing:

![lon](https://user-images.githubusercontent.com/7933853/50687415-856d2a80-1021-11e9-838a-d284b12e6b66.png)

because of the constrained satellite domain. I would like to plot this data using `xarray.plot.contourf`. So far, I've managed to plot using `xarray.plot.pcolormesh` , but only with a workaround where I replaced the missing values in the coordinate arrays with some dummy values.

The error message when I try to `contourf` the data using the coordinate arrays WITH missing values reads:
```
IllegalArgumentException: Points of LinearRing do not form a closed linestring
Shell is not a LinearRing
```

And the message WITHOUT missing values (substituted by dummy values):
```
TopologyException: side location conflict at 49.999999999999993 0
TopologicalError: The operation 'GEOSContains_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x130e75630>
```

Any help on plotting this data with `contourf` would be greatly appreciated. 

### Code to reproduce
See my notebook and example data here: https://github.com/lvankampenhout/bug-reports/tree/master/cartopy-contourf

### Cartopy version
Version of Cartopy tested: `0.16.0`
Version of Xarray tested: `0.10.4` and `0.10.9`

**Comment by pelson** [comment]
Hi @lvankampenhout. This really falls under the "Questions" category, which is best served through StackOverflow (much better visibility, and a better interface).

On the whole, it is important to remember that the contour algorithm is coming from matplotlib - it is an explicitly cartesian implementation. The good news is that your data is arranged in a cartesian grid (in the form of a 2d array), the bad news is that lats/longs do not describe this data in a cartesian grid.

You can see this by contouring your data with your x and y coordinates:

```
plt.contour(ds['x'], ds['y'], ds['lwp'][0])
```

So the trick is to figure out what coordinate system your data is in and using that as a coordinate system rather than lats/longs.

In your situation, I don't see the original coordinate system in the NetCDF file (perhaps the authors have documented it elsewhere?), so we could use a little bit of projection knowledge...

Your data is clearly centred at/around the North Pole / Greenland and is polar in its topology, so let's pick a projection that has these properties... there are many, but the simplest to instantiate in cartopy is ``NorthPolarStereo()``. You'd want to convert the lats and longs you have into this coordinate system and then have to deal with all the missing data / nans before passing these coordinates through to matplotlib (via cartopy).


```
# Convert the non-cartesian lats/lons to a sensible cartesian system.
nps = ccrs.NorthPolarStereo()
coords = nps.transform_points(
    ccrs.PlateCarree(), np.array(ds['lon']), np.array(ds['lat']), )
```

Next, handle the masked values:

```
xs = np.ma.masked_invalid(coords[..., 0])
ys = np.ma.masked_invalid(coords[..., 1])
data = np.ma.masked_invalid(ds['lwp'][0])

data.mask = np.logical_or(data.mask, xs.mask, ys.mask)

# Matplotlib's contour can't handle masked arrays.
# But it doesn't matter, as the data is now masked at these locations.
xs = xs.filled(0)
ys = ys.filled(0)
```

With this in place, you can contour your data:

```
plt.figure(figsize=(10, 10))
ax = plt.axes(projection=stereo)
plt.contourf(xs, ys, data, transform=nps)
ax.coastlines()
```
  
![download](https://user-images.githubusercontent.com/810663/51136596-cd1b5f80-1834-11e9-8edf-66c4fe03c16e.png)


Hope this is useful to you. Please consider StackOverflow in the future for these types of questions.

Best,

Phil
