### ISSUE TITLE
Natural Earth server down exception

### ISSUE THREAD

**Issue by enorazza** [SciTools/cartopy#1347]
In this moment the Natural Earth download hosting server is down.
http://naciscdn.org

Ok this is clearly not a Cartopy problem, but when I am composing the map there are a lot of things in there (points, lines, other stuff) that I would like to be rendered even if something is missing.
So, my code has something like this:
```
try:
lakes_north_america = cfeature.NaturalEarthFeature( category='physical', name='lakes_north_america', scale='10m', facecolor='none', edgecolor='blue', alpha=0.3)
ax.add_feature(lakes_north_america)
except: pass
```
This results in "timeout connection" global error.

The "try/except" statement seems to be completely uneffective bypassing the error.

In my opinion, Cartopy should walk throught the error, warning the user, but still trying to produce everything else.

Internet services are not there 100% of the time, they go up and down.. also my computer/server could have local internet problems, so it is better to add some "try/except" code during the download from Natural Earth (and other map services as well), because, strangely, I cannot do it by myself in my code, which was very unexpected.

**Comment by ajdawson** [comment]
The reason this does not work is because the data will not be fetched until you actually draw the plot.  The lines you have protected with the try/except block are not the ones that actually raise the exception.

It may well be a matter of preference as to whether an exception or a warning is used when data are not found, there are use cases for both, but cartopy has gone for raising an exception.

**Comment by enorazza** [comment]
Yeah thank you I suspected that.. I am going to close the issue since it is a clearly "won't fix" problem then.
