### ISSUE TITLE
Document test procedure

### ISSUE THREAD

**Issue by greglucas** [SciTools/cartopy#1371]
I find myself forgetting exactly what commands to run for the pytest test suite here. I think some kind of testing section in the readme just giving a few commands on how to test would be very useful.

I was running
`pytest --pyargs cartopy.tests`
or
`pytest --pyargs cartopy.tests.specific_test_file.py`
which I'm not even entirely sure is the best/right way to run the tests.

For example from matplotlib:
https://github.com/matplotlib/matplotlib#test
Maybe even a developer's guide page if you want to get really detailed?
https://matplotlib.org/devel/coding_guide.html#testing

**Comment by dopplershift** [comment]
I usually end up looking at `.travis.yml`, which has: `pytest -n 4 --pyargs cartopy`. Actually, last time I think `pytest lib/cartopy` worked fine for me.

But yes, it would be good to document.

**Comment by QuLogic** [comment]
This depends on how you've installed cartopy. As a full install, using `--pyargs` and a module path is the way to go. If you've done an editable install, then just running `pytest` by itself, or specifying a file in the repo works (because the 'install' is those same files.)

I have a tox config that could help codify things, but it's got some personal config that I don't know how to drop yet, plus it's got 312 environments (so far) that'd be a bit overwhelming for people.
