### ISSUE TITLE
get_extent not returning updated extent after set_aspect is set to equal in Cartopy

### ISSUE THREAD

**Issue by yportier** [SciTools/cartopy#1372]
See [this question](https://stackoverflow.com/questions/58003004/get-extent-not-returning-updated-extent-after-set-aspect-is-set-to-equal-in-cart) on SO, `get_extent()` does not return correct values until after plotting.

**Comment by greglucas** [comment]
You need to call `ax.apply_aspect()`, https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.axes.Axes.apply_aspect.html, after setting the extent. That method is called automatically when the `draw` method for the axis is called, which is why you see the adjustment after it has been plotted.

This should work as you expect I think:
```
ax.set_aspect('equal', adjustable='datalim', anchor='C')
ax.apply_aspect()
ext2 = ax.get_extent() # trying to get the updated extent
```

**Comment by yportier** [comment]
Perfect! That is indeed working as expected.
Many thanks
