### ISSUE TITLE
feature request... ability to remove a feature...

### ISSUE THREAD

**Issue by SpacelySpaceSprockets** [SciTools/cartopy#1385]
### Description

Simple feature request I think. I couldn't find this on stackoverflow or google.

I have an application written in pyqt and in it I have a lightly interactive map widget made with cartopy.  I would like to have checkboxes where people can click on them and have features added to or removed from the plot.  The add_feature will do half of that, but I don't see a remove_feature function

If there's a way to do that now (especially one that didn't require clearing and redrawing everything on the map) that would be greatly appreciated as well.

Cheers

#### Code to reproduce

```

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by dopplershift** [comment]
So `add_feature()` returns the matplotlib artist that was created and added to the plot, and these have both `remove()` and `set_visible()` methods that you can use:
```python
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1, projection=ccrs.LambertConformal())
ax.add_feature(cfeature.COASTLINE)
states = ax.add_feature(cfeature.STATES)
ax.set_extent((-130, -60, 20, 55))
#states.remove()
states.set_visible(False)
```

The difference is that `remove()` takes the artist off of the plot (which may result in it being deleted if you don't have a handle to it elsewhere). `set_visible` tells matplotlib not to draw it. I'm closing because I'm pretty sure that's what you're looking for, but feel free to re-open if there's something I missed.
