### ISSUE TITLE
Pixels not plotted with straight lines

### ISSUE THREAD

**Issue by MarkWieczorek** [SciTools/cartopy#1398]
I have a global grid of data in a numpy array that I would like to plot in a map projection. The data span longitudes from 0 to 360, and latitudes from -90 to 90. When plotting the grid using `imshow`, however, the upper and lower boundaries of the pixels are not plotted as straight lines, and are somewhat curved. This is all the more bizarre given that latitudes should be projected as straight lines in the PlateCarree projection I am using (other projections yield similar results).

![test](https://user-images.githubusercontent.com/8697285/69000219-72c3b300-08cc-11ea-8b84-3633fefaf149.png)

Here is the code used to generate the plot
```
import cartopy.crs as ccrs
interval = 30

# set the longitudes and latitudes to span 0-360 and 90 to -90.
lat = np.arange(90, -90-interval, -interval)
lon = np.arange(0, 360+interval, interval)
longrid, latgrid = np.meshgrid(lon, lat)

# make a grid of data that representats the function sin(lon)*cos(lat)
data = np.sin(np.deg2rad(longrid)) * np.cos(np.deg2rad(latgrid))

# set the extent of the data coordinates: the boundaries are extended by half a pixel in
# all directions since the function uses gridline coordinates.
extent=(lon[0]-interval/2, lon[-1]+interval/2, lat[-1]-interval/2, lat[0]+interval/2)

# plot using a PlateCarree projection
fig = plt.figure()
ax = fig.add_subplot(111, projection=ccrs.PlateCarree(central_longitude=180))
ax.imshow(data, transform=ccrs.PlateCarree(), extent=extent, origin='upper')
```
I note that when the interval between grid points is smaller, the images look *much* better. I was only using this large grid interval here because I was trying to figure out how Cartopy plots pixels and treats the image "extent" (there isn't any documentation on this but it appears to use the same conventions as in matplotlib: https://matplotlib.org/3.1.1/tutorials/intermediate/imshow_extent.html)

If it is of importance, I am using macOS with the most recent version of Cartopy on master, and all dependencies are up to date.

**Comment by dopplershift** [comment]
So that is weird, and shouldn't be happening. This problem actually goes away, though if you plot in the same coordinates as your specify your data--you're not doing this right now because you specify `central_longitude=180`. So if I do:
```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import numpy as np
interval = 30

# set the longitudes and latitudes to span 0-360 and 90 to -90.
lat = np.arange(90, -90-interval, -interval)
lon = np.arange(0, 360+interval, interval)
longrid, latgrid = np.meshgrid(lon, lat)

# make a grid of data that representats the function sin(lon)*cos(lat)
data = np.sin(np.deg2rad(longrid)) * np.cos(np.deg2rad(latgrid))

# set the extent of the data coordinates: the boundaries are extended by half a pixel in
# all directions since the function uses gridline coordinates.
extent=(lon[0]-interval/2, lon[-1]+interval/2, lat[-1]-interval/2, lat[0]+interval/2)

# plot using a PlateCarree projection
fig = plt.figure()
ax = fig.add_subplot(111, projection=ccrs.PlateCarree(central_longitude=180))
ax.imshow(data, extent=extent, origin='upper')
```

This tells `imshow` to that the data are in the same coordinate system as the projection set for the axes (it also works if you pass `central_longitude=180`). So that's a work-around.

I do think there's a bug here because shifting around by 180 degrees should not cause any actual warping, at least for PlateCarree.

**Comment by MarkWieczorek** [comment]
It appears that the pixels are being drawn as geodetic lines. Unfortunately, I don't see any options to disable this...

**Comment by dopplershift** [comment]
Well, it's trying to be correct, I guess. My question is: did you intend to use two different projections?

**Comment by MarkWieczorek** [comment]
Yes. The dataset is provided as being defined between 0/360E and 90/-90S, but I would like to make an arbitrary image where the user chooses the central_longitude.

**Comment by dopplershift** [comment]
You should be able to change this instead using `ax.set_extent()`.

**Comment by MarkWieczorek** [comment]
For completeness, here is an image generated by substituting `projection=ccrs.PlateCarree(central_longitude=180)`  with `projection=ccrs.Mollweide(central_longitude=180)`. As you can see, the problem persists....

![moll](https://user-images.githubusercontent.com/8697285/69043687-cbda3680-09f3-11ea-816f-105911b64b6a.png)

**Comment by dopplershift** [comment]
Well my first question is: are curved lines actually correct to represent lines of constant latitude on the Mollweide projection. My gut says no, but I'm by no means an expert in the attributes of projections.

**Comment by MarkWieczorek** [comment]
Latitude lines in a Mollweide projection are horizontal, just like PlateCarree, Hammer, Mercator, and a bunch of others.

**Comment by htonchia** [comment]
Well, when I read your code, you:

- create an image with lat lon coordinates
- keep the image (DATA) and throw way the coordinates
- compute an extent which goes beyond -90 and 90 for latitude
- imshow, with transform information,
    according to documentation
    transform: :class:`~cartopy.crs.Projection` or matplotlib transform
            The coordinate system in which the given image is
            rectangular.
- transform to the axes projection

When I read the cartopy code, it does compute coordinates in the
transform projection, but it does interpolate using distance to the
vertices, in XYZ geocentric, not in the DATA projection.
It explains why the straight lines don't stay straight.
I think the interpolation should have been done in the DATA projection.

So I think it is a bug.

I modified the code, because I didn't like the latitudes out of the -90, 90 range.

I have tested a fix that interpolate the source DATA at the same resolution
as the transformed DATA before the transformation to the target projection.

So if people agree that it is a bug, I can propose the fix.

Using that code, that goes beyond the original question as I have included Polar in the mix:
```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.path as mpath
import cartopy.crs as ccrs

INTERVAL = 30
MINLAT = -75
MAXLAT = 75
MINLON = -165
MAXLON = 75

PROJ_DATA = ccrs.PlateCarree(central_longitude=0)
PROJS = {}
PROJS['Plate Carre 180'] = ccrs.PlateCarree(central_longitude=180)
PROJS['Plate Carre 0'] = ccrs.PlateCarree(central_longitude=0)
PROJS['Plate Carre 225'] = ccrs.PlateCarree(central_longitude=225)
PROJS['Mollweide 180'] = ccrs.Mollweide(central_longitude=180)
PROJS['Polar -45'] = ccrs.NorthPolarStereo(central_longitude=-45)

PROJS2 = {}
PROJS2['Polar -45'] = ccrs.NorthPolarStereo(central_longitude=-45)
PROJS2['Polar 0'] = ccrs.NorthPolarStereo(central_longitude=0)
PROJS2['Plate Carre 180'] = ccrs.PlateCarree(central_longitude=180)
PROJ_DATA2 = PROJS2['Polar -45']

# set the longitudes and latitudes to span 0-360 and 90 to -90.
LAT = np.linspace(MAXLAT, MINLAT, (MAXLAT-MINLAT) / INTERVAL + 1)
LON = np.linspace(MINLON, MAXLON, (MAXLON-MINLON) / INTERVAL + 1)
LONGRID, LATGRID = np.meshgrid(LON, LAT)

# make a grid of DATA that representats the function sin(lon)*cos(lat)
DATA = np.sin(np.deg2rad(LONGRID)) + np.cos(np.deg2rad(LATGRID))+\
    0.2 * np.cos(np.deg2rad(LONGRID)) + 0.2 * np.sin(np.deg2rad(LATGRID))

# set the extent of the DATA coordinates: the boundaries are extended by half a pixel in
# all directions since the function uses gridline coordinates.
EXTENT = (LON[0]-INTERVAL/2, LON[-1]+INTERVAL/2, LAT[-1]-INTERVAL/2,
          LAT[0]+INTERVAL/2)

# in polar
EXTENT2 = [-12500000, 12500000, -12500000, 12500000]

# circle to make the boundary in polar stereographic
THETA = np.linspace(0, 2 * np.pi, 100)
CENTER, RADIUS = [0, 0], 12500000
VERTS = np.vstack([np.sin(THETA), np.cos(THETA)]).T
CIRCLE = mpath.Path(VERTS * RADIUS + CENTER)

# Plot from PROJ_DATA to other PROJS
for proj in PROJS:
    fig = plt.figure(figsize=(10, 6), dpi=100)
    axe = fig.add_subplot(111, projection=PROJS[proj])
    if 'Polar' in proj:
        axe.set_xlim(-12500000, 12500000)
        axe.set_ylim(-12500000, 12500000)
        axe.set_boundary(CIRCLE)
    else:
        axe.set_global()
    axe.imshow(DATA, transform=PROJ_DATA, extent=EXTENT, origin='upper')
    axe.set_title(proj)
    axe.coastlines()

# From here the image DATA is in polar stereographic projection
for proj in PROJS2:
    fig = plt.figure(figsize=(10, 6), dpi=100)
    axe = fig.add_subplot(111, projection=PROJS2[proj])
    if 'Polar' in proj:
        axe.set_xlim(-12500000, 12500000)
        axe.set_ylim(-12500000, 12500000)
        axe.set_boundary(CIRCLE)
    else:
        axe.set_global()
    axe.imshow(DATA[:, :5], transform=PROJ_DATA2, extent=EXTENT2, origin='upper',
               cmap='cool')
    axe.set_title(proj)
    axe.coastlines()
```

With the fix I have tested I get:
![Figure_9](https://user-images.githubusercontent.com/54799451/70374776-f171a600-18f6-11ea-86ed-1be3547f3716.png)

![Figure_10](https://user-images.githubusercontent.com/54799451/70374780-f5052d00-18f6-11ea-9992-bce4adc4d6a6.png)

![Figure_11](https://user-images.githubusercontent.com/54799451/70374783-f9c9e100-18f6-11ea-9535-65ac1123a6a2.png)

![Figure_12](https://user-images.githubusercontent.com/54799451/70374784-fe8e9500-18f6-11ea-9e0c-758a225f8ff0.png)

![Figure_13](https://user-images.githubusercontent.com/54799451/70374786-03ebdf80-18f7-11ea-8764-dad5613ae1a3.png)

![Figure_14](https://user-images.githubusercontent.com/54799451/70374792-1534ec00-18f7-11ea-8b04-959ec0583dff.png)

![Figure_15](https://user-images.githubusercontent.com/54799451/70374794-182fdc80-18f7-11ea-887c-9e5405cac2c1.png)

![Figure_16](https://user-images.githubusercontent.com/54799451/70374795-1cf49080-18f7-11ea-93ba-d09c5065ea85.png)

**Comment by MarkWieczorek** [comment]
This is indeed the behavior that I was expecting. I vote for making a PR. Thanks!

**Comment by dopplershift** [comment]
Moving the interpolation to data coordinates seems reasonable to me--and I think the images you've shown look good. Would love to have others (@pelson @QuLogic ?) weigh in as well.

**Comment by pelson** [comment]
I "weighed in" in the PR #1474 😆. Essentially, for better or worse, in cartopy we typically expect the coordinate reference system to define the "distance metric" (how to draw a line between two points), hence a line in ``ccrs.PlateCarree()`` and ``ccrs.Geodetic()`` look very different.

We *could* argue that the distance metric and the coordinate system should be defined independently, but so far the strategy has worked quite well for cartopy. The case being highlighted here is essentially that we are getting the equivalent of ``ccrs.Geodetic()`` interpolation, even when specifying the coordinates in a projected CRS (such as ``ccrs.PlateCarree()``. Perhaps we should change the behaviour to be consistent with other transformations (notably geometry/line transformations) and use cartesian interpolation for images when an ``extent`` is defined to have a projection CRS, but spherical interpolation (what we are seeing here) for ``ccrs.Geodetic()``.

There is an outstanding action in #1474 to propose a method of choosing the distance metric. Perhaps the above is the simplest and most consistent approach to doing so, even if it does mean a breaking behavioural change.

**Comment by greglucas** [comment]
This should be working as expected now on v0.20, closed by commit: https://github.com/SciTools/cartopy/pull/1808/commits/017f989f02078e8e41f60852713eb3760ef9b60b
Feel free to re-open if there is anything unexpected still.
