### ISSUE TITLE
central_longitude=0.0 and central_longtitude=0 give different results

### ISSUE THREAD

**Issue by MarkWieczorek** [SciTools/cartopy#1439]
I would like to project some simple data using a PlateCarree projection. When I set `central_longitude=0` everything works as expected, but if I specify `central_longitude=0.0` their are major problems, as shown in the image below.

```
import cartopy.crs as ccrs
interval = 30

# set the longitudes and latitudes to span 0-360 and 90 to -90.
lat = np.arange(90, -90-interval, -interval)
lon = np.arange(0, 360+interval, interval)
longrid, latgrid = np.meshgrid(lon, lat)

# make a grid of data that representats the function sin(lon)*cos(lat). Note that the value
# represents the center of a pixel.
data = np.sin(np.deg2rad(longrid)) * np.cos(np.deg2rad(latgrid))

# set the extent of the data coordinates: the boundaries are extended by half a pixel in
# all directions since the function uses gridline coordinates.
extent=(lon[0]-interval/2, lon[-1]+interval/2, lat[-1]-interval/2, lat[0]+interval/2)

# plot using a PlateCarree projection
fig = plt.figure()
ax1 = fig.add_subplot(121, projection=ccrs.PlateCarree(central_longitude=0))
ax1.imshow(data, transform=ccrs.PlateCarree(), extent=extent, origin='upper')
ax1.gridlines()
ax1.set_title('central_longitude=0')

ax2 = fig.add_subplot(122, projection=ccrs.PlateCarree(central_longitude=0.0))
ax2.imshow(data, transform=ccrs.PlateCarree(), extent=extent, origin='upper')
ax2.gridlines()
ax2.set_title('central_longitude=0.0')
```
![test](https://user-images.githubusercontent.com/8697285/72143487-12666480-3397-11ea-8e60-1e1a9d5b8678.png)

**Comment by greglucas** [comment]
I can reproduce. It looks like an issue with the `imshow` wrapping to me.
The problem is not just with `central_longitude=0`, but rather that the imshow transform is the same/different than the axis projection.
`axis_proj = ccrs.PlateCarree(0)`
`data_proj = ccrs.PlateCarree(0.)`

if `axis_proj == data_proj` then there is a shortcut path that imshow takes and simply plots the image on the current axes rather than warping/wrapping the image.
https://github.com/SciTools/cartopy/blob/da56f88528e21866c9370fe656ba5cdfc100a6d8/lib/cartopy/mpl/geoaxes.py#L1237-L1240
Your first axis you have different projections (one with `0`, the other default of `0.`), but in the second axis you have the same projection and the shortcut happens in imshow.

In your second case, the xlim of the axis is (-15, 375) instead of (-180, 180) which would match the extent of the axis.

It definitely seems like a bad feature (bug) to me.
