### ISSUE TITLE
Colab server is getting crash every time when I run the below code to plot using cartopy 

### ISSUE THREAD

**Issue by shalin07** [SciTools/cartopy#1489]
I'm using CMIP data for analysis. And I have Xarray dataset with following info:

`Coord:`
`lat: float64 (192)`
`lon: float64 (288)`
`time: object (1200) (monthly data)`

`Data Variables:`
`tas: (time, lat, lon)`
`float32`
`dask.array `

When I try to plot temperature for some specific date it's taking 15-20 mins to plot. So I found a way and I converted dask array to regular uisng:

`.load( )`

And now when i plot that same thing it's getting plot in 1 sec. But now I'm running into another problem. I want coastlines on that plot so I'm using cartopy library for that. Here's my code for that:

`
from cartopy import config`
`import cartopy.crs as ccrs`
`temp=monthly_mean['tas']`
`ax = plt.axes(projection=ccrs.PlateCarree())`
`temp[0, :, :].plot(ax=ax, transform=ccrs.PlateCarree())`
`ax.coastlines()
`
Now whenever I run this code my colab server is getting crash. I don't know what is going wrong. When I try to do same thing before converting dask array, it's plotting with coastlines and everything I want but as usual it's taking 15 mins to plot.

**Comment by pelson** [comment]
Thanks for raising @shalin07. Unfortunately there isn't really enough to go on here in order to track down the issue. Please could you provide the software versions you are using, as well as the full traceback/stack-trace of the exception/crash? There was a question recently regarding colab at #1346, perhaps this will be helpful, or at least give you some idea of some of the information that is needed in order to help you.

Since there isn't anything we can action here until we have more information, I'll close the issue with the intention that you can re-open it (I think you have the power to do so, but if not please let us know) with the missing details.

Cheers,

**Comment by shalin07** [comment]
@pelson Sure you can close it, I switched to basemap and it worked!

**Comment by greglucas** [comment]
Just so you know, @shalin07, basemap is currently end of life and not really supported much anymore. If you do decide to give Cartopy another try and are still running into issues feel free to reopen and add the additional details.
