### ISSUE TITLE
How to remove latitude labels in x axis in cartopy 0.18

### ISSUE THREAD

**Issue by smartlixx** [SciTools/cartopy#1530]
### Description

When I test the beta version of 0.18, I find some weird behavior in the new gridliner labels. While I can fix most of them by digging into the code, one thing I can't change is that there are sometimes latitude labels in x axes and longitude labels in y axes. Is there any way to disable this behavior?

#### Code to reproduce
    import cartopy.crs as ccrs
    import matplotlib.pyplot as plt

    lamber_crs = ccrs.LambertConformal(central_longitude=105) 
    ax0 = plt.axes(projection=lambert_crs)
    ax0.set_extent([70, 140, 15, 52], crs=ccrs.PlateCarree())
    gl = ax0.gridlines(draw_labels=True, dms=True, x_inline=False, y_inline=False)
    gl.top_labels = gl.right_labels = False
    gl.rotate_labels = False
    ax0.coastlines(resolution='10m')
    plt.show()
```

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>
 python 3.7

 cartopy 0.18b2

![image](https://user-images.githubusercontent.com/16891009/80019437-1c594100-850a-11ea-845a-d378211f278f.png)

### conda list

```
```

### pip list

```
```

</details>

**Comment by QuLogic** [comment]
@greglucas So this is probably why we need more label options...

**Comment by greglucas** [comment]
I agree that there could be more options, or maybe just more descriptive options. I'm just not sure it is a trivial addition. Map boundaries are not really well-defined to be rectangular and what is left/right/top/bottom all the time, so it would need some thinking.

For this case, the default probably isn't ideal, but you can still at least choose what gridlines you want or not explicitly, which can be added with:
```python
gl.xlocator = mticker.FixedLocator([80, 100, 120])
gl.ylocator = mticker.FixedLocator([20, 30, 40])
```

Another problem is that when you move the map around on pan/zoom, the gridliner text is all static and attached to the background rather than staying on the boundary like a normal mpl ticker. So the gridlines and text are pretty useless in interactive mode.

**Comment by QuLogic** [comment]
We do have the 4 lists:
```
          self.bottom_label_artists = []
          self.top_label_artists = []
          self.left_label_artists = []
          self.right_label_artists = []
```
I think bottom/top and left/right are just defined by whether the 'other' coordinate is a minimum or a maximum. We don't save whether it's lat/lon in those lists, but I guess we could and use that information for labelling options.

**Comment by greglucas** [comment]
There are still some issues with thinking about lat/lon and whether the projection is rotated. I was looking at the US map gridline figures: https://github.com/SciTools/cartopy/blob/master/lib/cartopy/tests/mpl/baseline_images/mpl/test_gridliner/gridliner_labels_inline_usa_1.5.png

and quite a few of them actually have the coordinate system rotated so the latitudes are on the top/bottom rather than left/right like you'd naturally think about. This could probably be incorporated into the code by seeing what the axes projection rotation is, but I still think it will be a fairly difficult undertaking to get right.

**Comment by stefraynaud** [comment]
It's a bug: for example, the 140°E label is first identified as a bottom label because it has an angle of -67°, thus kept on the figure, then it is rotated in ``_update_labels_visibility`` to be properly displayed without overlapping the map boundary, so that we think it is a right label.
One solution is to move the side label visibility and the alignment specs also from ``draw_gridliner`` to to this method ``_update_labels_visibility`` .

**Comment by smartlixx** [comment]
Thanks, @stefraynaud. This almost solved my problem, except that there is still a '70 E' in the left axis. The code to reproduce the problem is as follows:

```python
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature
    import matplotlib.pyplot as plt
    import matplotlib.ticker as mticker

    lambert_crs = ccrs.LambertConformal(central_longitude=105) 

    ax0 = plt.axes(projection=lambert_crs)
    ax0.set_extent([75, 130, 18, 54], crs=ccrs.PlateCarree())
    ax0.add_feature(cfeature.LAND)
    ax0.add_feature(cfeature.BORDERS)
    gl = ax0.gridlines(draw_labels=True, dms=True, x_inline=False, y_inline=False)
    gl.xlocator = mticker.FixedLocator([70, 80, 90, 100, 110, 120, 130])
    gl.ylocator = mticker.FixedLocator([10, 20, 30, 40, 50])
    gl.rotate_labels = False
    gl.top_labels = gl.right_labels = False
    ax0.coastlines(resolution='10m')
```
 
The output is shown in the attached picture. Pay attention to the '70 E' in the left labels

![image](https://user-images.githubusercontent.com/16891009/80483583-e80dd680-8988-11ea-8e7d-97569c4e94cd.png)

**Comment by stefraynaud** [comment]
Okay.
Now it's a problem of options, and it is simply not implemented.
As said before by @greglucas, more option could be added.
One way: ``left_labels`` for instance could be set to ``True``, but also to ``"x"`` or ``"y"`` to select to kind  of labels to accept.

**Comment by greglucas** [comment]
So the quick solution here may be to use two girdliners, one with your subselection of labels you want (and `xlines = ylines = False`)and one with all of the lines you want and `draw_labels = False`.

I like the idea of left_labels with True, x, y as options.

I guess I'm still slightly confused as to what is considered left/right/top/bottom for some of the plots. Is that purely determined by angle? I guess I still think that it is an ambiguous case where lat/lon lines will be intersecting on the boundary of the plane somewhere and we'll have to decide in some semi-arbitrary way what to do in a default case.

**Comment by stefraynaud** [comment]
Yes, left/right/top/bottom sides identifier are purely determined avec the angle.
This is not robust, but it works in most situations, even on map with no rectangular boundaries, like Orthographic (what are the sides of a sphere?) and 
![Orthographic](https://scitools.org.uk/cartopy/docs/latest/_images/projections-10.png)
![InterruptedGoodeHomolosine](https://scitools.org.uk/cartopy/docs/latest/_images/projections-16.png).

To make it more robust, purely vertical and horizontal boundary segments should be identified, knowing that a boundary may be a mix of linear and non-linear limits.
I won't have time for now to go deeper into this direction.

**Comment by stefraynaud** [comment]
Here is an example of mixed boundary:
![mix_boundary](https://user-images.githubusercontent.com/1941408/80570632-71f68780-89fb-11ea-8fe7-676c34c4ca06.png)

I think I have an idea of a simple hack that use the left/right/top/bottom spines to determine a label side in conjunction with the geo spine.

**Comment by jeffreymei** [comment]
> We do have the 4 lists:
> 
> ```
>           self.bottom_label_artists = []
>           self.top_label_artists = []
>           self.left_label_artists = []
>           self.right_label_artists = []
> ```
> 
> I think bottom/top and left/right are just defined by whether the 'other' coordinate is a minimum or a maximum. We don't save whether it's lat/lon in those lists, but I guess we could and use that information for labelling options.

Can I ask when are these artists created? Or, can I use them to manually override the labelling?

 I was redirected here from issue #1576 . Below is the code I am using - you can see for example, the 40W label is shown on both the 'top' and 'right' artists, and if I call gl.top_label_artists I do get the Text(x, y, '40W') etc. But if I try to 'clear' the artists with gl.right_label_artists = [], it doesn't change anything. Also below you can see I tried the gl.right_labels=False but it didn't remove the right labels either.

ax = plt.subplot(111, projection=ccrs.SouthPolarStereo())
land = cfeature.NaturalEarthFeature('physical', 'land', '50m')
polar_crs = ccrs.SouthPolarStereo()
polar_extent = [-15, -120, -80, -66]
gl = ax.gridlines(color='r', draw_labels=True, x_inline =False, y_inline =True)
ax.set_extent(polar_extent, crs=ccrs.PlateCarree())
gl.right_label_artists=[]
gl.ylocator = mticker.FixedLocator([-85, -80, -75, -70, -65])
gl.xlocator = mticker.FixedLocator(np.arange(-160, 0, 20))
gl.right_labels=False
ax.add_feature(land, facecolor='#AAAAAA')
plt.show() 

![Figure_1](https://user-images.githubusercontent.com/3510683/85775876-2e17ba00-b6ee-11ea-9b0f-c44b6d95e96c.png)
