### ISSUE TITLE
Crimea is wrongly moved to the Russia

### ISSUE THREAD

**Issue by johngull** [SciTools/cartopy#1630]
Wanted to use your library to make some heatmaps on the country levels.
And found that you have wrong shapes for Ukraine and Russia, more precisely in your shapes, Crimea belongs to Russia. 
This obviously contradicts international understanding. With this mistake, you hiddenly push all library users to break international laws on their graphs. 

I hope you will fix this fast.

**Comment by greglucas** [comment]
All of the shapefile data is from the [Natural Earth](https://www.naturalearthdata.com/) project. Cartopy simply downloads and plots those for you. If you want to provide your own shapefiles you can do that as well. It looks like there are already several issues over at NaturalEarth brought up about this specific topic: https://github.com/nvkelso/natural-earth-vector/issues/390, https://github.com/nvkelso/natural-earth-vector/issues/391

Closing because this is external to Cartopy.

**Comment by johngull** [comment]
@greglucas Thanks for pointing this out.
Anyway, that will be nice if you will inform "Natural Earth" that your project suffer from their mistake.

And thanks for the nice library :)
