### ISSUE TITLE
Shapefile gives warning with GSHHS feature

### ISSUE THREAD

**Issue by MHBalsmeier** [SciTools/cartopy#1659]
Hi,
shapefile gives me a warning when I save a figure which has GSHHS features in it. Thought I'd ask it here:

MWE:

```python
import matplotlib.pyplot as plt;
import cartopy.crs as ccrs;
import cartopy;
fig = plt.figure();
proj = ccrs.Mercator(central_longitude = 0);
ax = plt.axes(projection = proj);
ax.add_feature(cartopy.feature.GSHHSFeature(levels = (1, 2), linewidth = 2.0));
print("before");
fig.savefig("test.png");
print("after");
```
output:

before
```
/home/max/.local/lib/python3.8/site-packages/shapefile.py:385: UserWarning: Shapefile shape has invalid polygon: no exterior rings found (must have clockwise orientation); interpreting holes as exteriors.
  warnings.warn('Shapefile shape has invalid polygon: no exterior rings found (must have clockwise orientation); interpreting holes as exteriors.')
```
after

What is the cause of this and how can it be resolved?

OS: Ubuntu 20.04
Cartopy: 0.18.0
pyshp: 2.1.2

Thanks in advance.

**Comment by dopplershift** [comment]
Since the warning is coming from `/home/max/.local/lib/python3.8/site-packages/shapefile.py:385`, I think this is an issue between the GSHHS data and pyshp. It may be worth asking on the [pyshp issue tracker](https://github.com/GeospatialPython/pyshp/issues). Having said that, it looks like we are currently using an old copy of the GSHHS data (2.2.0 while 2.3.7 is the latest), so it's possible using a newer copy of the data would fix it--which is covered in #1353. Closing since the only thing CartoPy could do is update, and that's already covered in another issue.

**Comment by MHBalsmeier** [comment]
thanks, updating the coastline data solved it

**Comment by karimbahgat** [comment]
In short, the warnings are nothing to worry about. It's just a notification caused when trying to produce the GeoJSON representation of two weird slivers in the `GSHHS_c_L1.shp` shapefile (downloaded from the most recent cartopy GitHub repo), at shapefile index 95 and 471. They are both single-part polygons but have the ring orientation of an interior hole (i.e. holes without an exterior polygon). PyShp assumes they were meant to be exterior polygons and includes them in the GeoJSON, and notifies the user. I just made some commits that improved the somewhat cryptic warning messages, reports which shapes were affected, and allows users to disable the warning messages. Should be available in the next version.
