### ISSUE TITLE
Unable to `pip install cartopy` in Ubuntu Docker Container

### ISSUE THREAD

**Issue by bjwhite-fnal** [SciTools/cartopy#1838]
### Description

Hi!
After following your directions for installation of external Linux dependencies, I'm still unable to install Cartopy via pip into a Ubuntu-based (20.04.3LTS) Docker container. 
```
ERROR: Could not build wheels for cartopy which use PEP 517 and cannot be installed directly
```

#### Code to reproduce

A copy of my Dockerfile is below. It can easily be built with a trivial `docker build` command.
```
# Run a Jupyter notebook on localhost
FROM jupyter/minimal-notebook

USER root
# Install cartopy deps
RUN apt-get -y update && apt-get -y upgrade && apt-get -y install gcc libgeos-dev libproj-dev proj-bin

USER jovyan
RUN pip3 install --upgrade pip setuptools wheel && pip3 install cython pyproj matplotlib scipy scikit-learn seaborn pandas xarray pyshp shapely 

# Everything works fine up to installation of cartopy
RUN pip3 install cartopy
```

#### System Libraries
You can recreate this easily enough from the Dockerfile, but I attached a listing of all installed packages in the container.
[libs.txt](https://github.com/SciTools/cartopy/files/7110639/libs.txt)

**Comment by QuLogic** [comment]
> apt-get -y install gcc libgeos-dev libproj-dev proj-bin

You forgot the C++ compiler.

But since you're using a Jupyter image with conda/mamba installed, why not use a conda environment to get a precompiled Cartopy?

**Comment by bjwhite-fnal** [comment]
Aha, thank you @QuLogic. Honestly I was just trying to build it without conda to see how hard it was. I appreciate your response.

**Comment by Eisbrenner** [comment]
@QuLogic Hej, I just came across this while looking for the unnamed dependencies of `pip3 install cartopy` and since I'm here I may add my reason for building a new conda-free container today although I already had a conda version running.
The reason being that I added a new dependency and conda takes several hours to solve its dependecies while pip may takes 5 minutes. In fact I started building the new container while the other one was building, still not finished and I have in the meantime build the new container, inclusing a length internet search to find the cartopy dependencies for a container build.
