### ISSUE TITLE
Incorrect link at the top of the cartopy Gallery

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1865]
The _getting started_ link at the top of the [Gallery](https://scitools.org.uk/cartopy/docs/latest/gallery/index.html), in

_For more examples, tutorials, and guides on how to use Cartopy, see the [getting started](https://docs.python.org/3/library/unittest.mock-examples.html#getting-started) section_.

is obviously wrong. I guess it should be a link to https://scitools.org.uk/cartopy/docs/latest/index.html#getting-started

**Comment by greglucas** [comment]
@jypeter, we did a major overhaul of the documentation for the next release. Can you check the latest documentation builds and see if you find any issues there? I think this issue is fixed in the header link.

This is the link to the latest build on master: https://2816-5282596-gh.circle-artifacts.com/0/docs/build/html/index.html

**Comment by greglucas** [comment]
OK, I'm going to close this issue then. But, please feel free to open new issues if you find problems in the new documentation.
