### ISSUE TITLE
Save to geotiff

### ISSUE THREAD

**Issue by bblay** [SciTools/cartopy#295]
Save a plot to geotiff.

```
plt.contourf(data)
plt.gca().coastlines()
something.something("out.geotiff")
```

Moved from [Iris issue #574](https://github.com/SciTools/iris/issues/574)

**Comment by dara74k** [comment]
Hi, I am using cartopy to plot radar data and would like to save the output as geotiff. Currently, I am using matplotlib and it only supports certain extensions (e.g. png, tiff)
Thanks

**Comment by pp-mo** [comment]
Hi @dara74k 
I think saving to GeoTiff is basically an operation on data, not really a "plotting" issue.

For example, we do have some (rather thin + simplistic, experimental) code for this in Iris : https://github.com/SciTools/iris/blob/v2.2.0/lib/iris/experimental/raster.py
If you can wade through the Iris-y bits there, the essential mechanics are pretty simple : the key functions are performed by GDAL, and this code shows how to do it.
In the meantime, this uses almost no other functionality from Iris, or even in fact from Cartopy.  

So that might sound like a reasonable argument for including such a function in Cartopy...

... However, the key problem with this is that GDAL is a pain to build and even more of a pain to resolve all dependencies with other packages.  Hence why the docstring isn't routinely built + published in the Iris docs (see: https://scitools.org.uk/iris/docs/latest/iris/iris/experimental/raster.html) .
( Summary :  we don't have GDAL as a core dependency of Iris, we don't install it into our docs-build, and so don't build docs for this routine in the standard docs-build. )

For those reasons, I guess we are even **_less_** likely to adopt GDAL as a dependency of Cartopy, which is generally much lighter in its dependencies than Iris.
I'm sorry I don't have a more definite suggestion here :  we have struggled a long time with this problem !

P.S. this does seem an odd place to make your comment.
Would you like to make an issue of it ?

**Comment by Sieboldianus** [comment]
Anyone stumbling upon this, here is what I did after wading through this:

```
conda install -c conda-forge flopy
```

```python
import flopy
from flopy.export.utils import export_contourf

cf = plt.contourf(data)
export_contourf(
     'contours.shp', 
    cf
```

Then use any external tool to confert shapefile to GeoTiff/Raster.
