### ISSUE TITLE
Global Stereographic plots contain a broken polygon when plotted as pcolormesh

### ISSUE THREAD

**Issue by mikewalker92** [SciTools/cartopy#323]
```
import iris
import cartopy
import matplotlib.pyplot as plt
import iris.quickplot as qplt
import cartopy.crs as ccrs

cube = iris.load_cube(iris.sample_data_path('A1B.2098.pp'))

plt.axes(projection=ccrs.Stereographic())

qplt.pcolormesh(cube)

plt.show()
```

The code above generates the following image;

![stereographic1](https://f.cloud.github.com/assets/4940023/1042176/4ba0403a-0fe6-11e3-93d3-facfa1b26a4e.png)

Zooming in onto the earth itself using the set_global command, we get;

![stereographic2](https://f.cloud.github.com/assets/4940023/1042186/73bd6016-0fe6-11e3-8551-9c1ba8030c5b.png)

This issue is repeated on all global cubes (tested on all cubes in Iris Sample Data). The same cubes plot normally if contour(f) is used instead. 
It appears to be due to a polygon being incorrectly transformed around the pole.

**Comment by pelson** [comment]
Still an issue. Looks like a bit of digging into the geometry is needed.

**Comment by pelson** [comment]
When I run this with mpl 3 and iris 2 I get a correctly zoomed plot, but the pcolormesh is incorrect (easier to see with ``cmap="Reds"``):

![figure_1](https://user-images.githubusercontent.com/810663/50781300-eb191b00-129c-11e9-9185-c496ff196d1b.png)


The remaining issue here is to dig into this (by looking at the geometries (not) being transformed by pcolormesh). I suspect the problem is that pcolormesh has a particular definition of when it needs to do special wrapping of polygons, and it is that which is going wrong. It may be relatively easy to fix this case (PR welcome), but it would be great to reconcile pcolormesh's definition of what needs wrapping with ``project_segment``'s.

**Comment by rcomer** [comment]
This appears to have been fixed at some point.  With latest everything (Cartopy 0.22, Matplotlib 3.8, Iris 3.7) I have

```python
import cartopy.crs as ccrs
import iris
import iris.quickplot as qplt
import matplotlib.pyplot as plt

cube = iris.load_cube(iris.sample_data_path('A1B.2098.pp'))

fig, ax_dict = plt.subplot_mosaic(
    "P;S", figsize=(5, 7), height_ratios=[2, 3], layout='compressed',
    per_subplot_kw=dict(P=dict(projection=ccrs.PlateCarree()),
                        S=dict(projection=ccrs.Stereographic())))

for ax in ax_dict.values():
    ax.coastlines()
    qplt.pcolormesh(cube, axes=ax)

plt.show()
```
![test](https://github.com/SciTools/cartopy/assets/10599679/e16a831c-ab96-402b-b859-066bf2a36c55)

Please re-open if I have misunderstood.
