### ISSUE TITLE
Upgrade tests to use matplotlib v1.4/v1.5

### ISSUE THREAD

**Issue by pelson** [SciTools/cartopy#354]
Deprecate v1.2.0 support after v0.10.

**Comment by QuLogic** [comment]
Travis seems to be using 1.3.1, so I guess this is fixed?

**Comment by pelson** [comment]
Seems reasonable. Maybe we should re-use the issue to upgrade to v1.4 (or v1.5 when it arrives)

**Comment by QuLogic** [comment]
@pelson Do you know if figure autoscaling was changed in 1.4 of matplotlib? It's the only thing that's causing a really big difference in results. For example, `test_view_lim_autoscaling` produces:
```python
AssertionError: 
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([[ 86.125047,  52.516846],
       [ 86.69595 ,  52.862473]])
 y: array([[ 86.124337,  52.515705],
       [ 86.696966,  52.863721]])
```

**Comment by QuLogic** [comment]
These images require a small change to the baseline due to minor differences in the corners of the axes lines (~0.1-0.3 RMS):
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_img_transform/regrid_image.png`
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/barbs_plate_carree.png`
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/global_scatter_wrap.png`
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/multiple_projections1.png`
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xticks_cylindrical.png`
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xticks_no_transform.png`
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xyticks.png`
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/yticks_cylindrical.png`
* `lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/yticks_no_transform.png`

These tests show larger issues:
 * `cartopy.tests.mpl.test_mpl_integration.test_global_contourf_wrap_new_transform`, `cartopy.tests.mpl.test_mpl_integration.test_global_contourf_wrap_no_transform` (RMS: 52.1623094959) - caused by matplotlib/matplotlib@f511ef93d2bdc088f0a16b1fb6b3d953ed437b18
 * `cartopy.tests.mpl.test_mpl_integration.test_global_pcolor_wrap_new_transform`, `cartopy.tests.mpl.test_mpl_integration.test_global_pcolor_wrap_no_transform` (RMS: 63.0321072395) - caused by matplotlib/matplotlib@e586c09fadbd79bb32d2b0f1149ef44b03bd439a + matplotlib/matplotlib@f511ef93d2bdc088f0a16b1fb6b3d953ed437b18
 * `cartopy.tests.mpl.test_mpl_integration.test_streamplot` (RMS: 48.1312590543) - caused by matplotlib/matplotlib@5ab1a680473ca8f13dadd6617880497c5f801c75
 * `cartopy.tests.mpl.test_set_extent.test_view_lim_autoscaling` - caused by matplotlib/matplotlib@b8726d09026ba7507d8501de0fbd921ec2d1243e

**Comment by QuLogic** [comment]
Except for that first `streamplot` change, I think these are all intended changes and/or bugfixes, so I'm inclined to simply replace the baseline images.

**Comment by QuLogic** [comment]
There's one more change causing failures with 1.4.3:
* `cartopy.tests.mpl.test_mpl_integration.test_pcolormesh_goode_wrap` (RMS: 32.5231528534), `cartopy.tests.mpl.test_mpl_integration.test_pcolormesh_mercator_wrap` (RMS: 26.5532499842). - caused by matplotlib/matplotlib@44ff97e30c03afe6a340b3d256bd04efff5808d0

I think this one might be a bug. The left edge is cropped a little bit, and it's pretty evident from the Interrupted Goode Homolosine image.

**Comment by QuLogic** [comment]
With 1.5.x, there are some more images with small changes (RMS < 1):
 * `cartopy.tests.mpl.test_features.test_gshhs`
 * `cartopy.tests.mpl.test_images.test_imshow`
 * `cartopy.tests.mpl.test_images.test_imshow_projected`
 * `cartopy.tests.mpl.test_images.test_pil_Image`
 * `cartopy.tests.mpl.test_images.test_stock_img`
 * `cartopy.tests.mpl.test_mpl_integration.test_barbs`
 * `cartopy.tests.mpl.test_web_services.test_wms`
 * `cartopy.tests.mpl.test_web_services.test_wmts`
All are caused by matplotlib/matplotlib@2a178393c00d0d234c4b59c190cc26fb6eee5cd7 (upgrade to Agg) and since they are nearly invisible, I think simply replacing them is the way to go.

There are a few more larger changes to bisect...

**Comment by QuLogic** [comment]
It turns out almost all the images need to regenerated due to the above mentioned upgrade of Agg in the upcoming matplotlib 1.5.0. There are a couple other major differences:

* `cartopy.tests.mpl.test_examples.test_global_map` (RMS: 0.777689776768), `cartopy.tests.mpl.test_mpl_integration.test_global_map` (RMS: 0.585012464255), `cartopy.tests.mpl.test_mpl_integration.test_multiple_projections` (RMS: 1.87054537502) - caused by matplotlib/matplotlib@37927b2228c9e46bcbba8d6df97002b8978ab06e
* `cartopy.tests.mpl.test_gridliner.test_grid_labels` (RMS: 25.706532414), `cartopy.tests.mpl.test_img_transform.test_regrid_image` (RMS: 4.26279634356), `cartopy.tests.mpl.test_shapely_to_mpl.test_contour_interiors` (RMS: 15.1097057659), `cartopy.tests.mpl.test_ticks.test_set_xticks_cylindrical` (RMS: 4.71076095233), `cartopy.tests.mpl.test_ticks.test_set_xyticks` (RMS: 6.46914144226), `cartopy.tests.mpl.test_ticks.test_set_yticks_cylindrical` (RMS: 8.16085320294), `cartopy.tests.mpl.test_ticks.test_set_yticks_no_transform` (RMS: 8.41449505813) - caused by matplotlib/matplotlib@c6d01835816ace3204212d072da1ac3af2b54997

I think both of the above are intended changes.

**Comment by QuLogic** [comment]
You can see the resulting images in [this branch](https://github.com/QuLogic/cartopy/tree/mpl-update). There is still something weird going on because `cartopy.tests.mpl.test_images.test_imshow` and `cartopy.tests.mpl.test_images.test_pil_Image` both fail even though they byte-for-byte produce the same image as expected.

**Comment by QuLogic** [comment]
@pelson Let me know if we should file any bugs in matplotlib; not sure we'll be able to get them into 1.5.0, at this point.

**Comment by pelson** [comment]
This is awesome work @QuLogic - super thorough, and really useful, thank you!

> Let me know if we should file any bugs in matplotlib

Yes we should. Whether they are fixed in 1.5 or a subsequent release is not as important as ensuring we report them.


Next steps: I think we should consider our image testing strategy within cartopy - the many minor differences in agg rendering show that we are way to sensitive to minor rendering changes, yet some of the other tests show that we are way too *insensitive* to some other key changes. Obviously we are not going to solve that problem here and now, but it is worth mentioning and starting to think about.

As for next steps, I think it would be healthy to be able to run the cartopy's matplotlib tests against multiple matplotlib versions for a few releases before we drop support for v1.3. Doing so means we need to define a results structure which allows us to have multiple image result directories (based on the matplotlib version). Would you mind taking a look at that?

The next concern is the fact that the cartopy repository is only getting bigger due to these image changed. Already I find it frustrating to do a clean checkout of the cartopy repo due to the time to download, for some reason my git seems to throttle after a number of Mb. One option then would be to pull *all* of the image tests out of the core repository, and to put them into their own repo which we link to in here (perhaps using git submodules). What are your thoughts on doing that?

**Comment by rhattersley** [comment]
> One option then would be to pull all of the image tests out of the core repository, and to put them into their own repo

**Comment by QuLogic** [comment]
I opened a report for matplotlib/matplotlib@5ab1a680473ca8f13dadd6617880497c5f801c75 (matplotlib/matplotlib#5369) and matplotlib/matplotlib@44ff97e30c03afe6a340b3d256bd04efff5808d0 (matplotlib/matplotlib#5370.)

I believe matplotlib/matplotlib@e586c09fadbd79bb32d2b0f1149ef44b03bd439a, matplotlib/matplotlib@e8f035d17800dc935c5b838ab23cb83827faf384, matplotlib/matplotlib@2a178393c00d0d234c4b59c190cc26fb6eee5cd7, matplotlib/matplotlib@37927b2228c9e46bcbba8d6df97002b8978ab06e, and matplotlib/matplotlib@c6d01835816ace3204212d072da1ac3af2b54997 are intended changes.

I am not sure about matplotlib/matplotlib@f511ef93d2bdc088f0a16b1fb6b3d953ed437b18 and matplotlib/matplotlib@b8726d09026ba7507d8501de0fbd921ec2d1243e.

**Comment by pelson** [comment]
> matplotlib/matplotlib@44ff97e (matplotlib/matplotlib#5370.)

I've been digging on this, and while the result is different, I think the problem is related to the new need to do a relim and autoscale_view as per https://github.com/SciTools/cartopy/issues/647#issuecomment-169247571. Some investigation of why this has come about is needed - it may be that the draw pipeline has changed subtly, and we need to account for that in the ``draw`` call on GeoAxes.

**Comment by QuLogic** [comment]
So what's the minimum matplotlib version to support?

**Comment by pelson** [comment]
> So what's the minimum matplotlib version to support?

Somewhat arbitrarily v1.3. One of my own motivations for that is my employers stack is still on that version currently.

**Comment by QuLogic** [comment]
> cartopy.tests.mpl.test_images.test_imshow and cartopy.tests.mpl.test_images.test_pil_Image both fail even though they byte-for-byte produce the same image as expected.

OK, I figured out this one; they both produce a different image from the stored one, but the other test that uses the same result overwrites it with the correct one. A bit of a peril of re-using the same result image name.

**Comment by QuLogic** [comment]
I think maybe `mpl/baseline_images/mpl/test_mpl_integration/pcolormesh_limited_area_wrap.png` got broken somehow.

**Comment by QuLogic** [comment]
Also, the new-ish `mpl/baseline_images/mpl/test_shapely_to_mpl/poly_interiors.png` is slightly different, maybe due to different snapping.

**Comment by QuLogic** [comment]
Should be done now.
