### ISSUE TITLE
Disappearing contours (again)

### ISSUE THREAD

**Issue by ajdawson** [SciTools/cartopy#478]
From an issue in the Iris support list: https://groups.google.com/forum/?fromgroups=#!topic/scitools-iris/rOtALjvfvVU

It looks like certain contours are being lost during transform/plotting. The plots are successful using `pcolormesh()` or matplotlib's `contourf()`, but not cartopy's `contourf()`.

@pelson - any ideas?

**Comment by pelson** [comment]
This *particular* issue turned out to be very specifically an anti-aliasing artifact. The order that you draw lines which are anti-aliased is important. If you draw a small geometry last, and it is anti-aliased, it will have the effect of growing when aliased with the surrounding pixels. If you draw a small geometry first, other geometries will grow into the area and will give the appearance of the geometry shrinking.

There is nothing more to be done about this - it is a fundamental drawing property which cannot be averted if a geometry is visualised without sufficient resolution.
