### ISSUE TITLE
imshow image doesn't appear

### ISSUE THREAD

**Issue by kjordahl** [SciTools/cartopy#643]
I'm trying to project an image plot into axes that have been created with a projection different from those of the image itself. I would expect the following to work, but the image does not show up.

Here's a minimal example:

```
import numpy as np
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

utm18n = ccrs.UTM(18)
merc = ccrs.Mercator()
left, bottom = 583057.357, 4511050.6293795705
right, top = 588814.059052222, 4516255.36
a = np.random.random((10, 10))

ax = plt.axes(projection=merc)
plt.title('Mercator')
ax.imshow(a, origin='upper', transform=utm18n,
          extent=(left, right, bottom, top), cmap='gray',
          interpolation='nearest')
x = [left, right, right, left, left]
y = [bottom, bottom, top, top, bottom]
ax.coastlines(resolution='10m', linewidth=4, color='red')
ax.gridlines(linewidth=2, color='lightblue', alpha=0.5, linestyle='--')
ax.set_extent((left, right, bottom, top), utm18n)

plt.show()
```

The grid and coastlines do appear correctly.

If I do the same thing with `ax = plt.axes(projection=utm18n)`, which is the image's native projection, it works (and doesn't have to reproject the image).

**Comment by kjordahl** [comment]
The script on which this example was based is [here](https://github.com/kjordahl/SciPy-Tutorial-2015/blob/master/examples/rasterio_cartopy.py).

**Comment by ajdawson** [comment]
@kjordahl - If you set the extent of the plot before you call `imshow()` this should work fine. The reason is that the image is re-projected (interpolated) once with a set resolution, to match the current axes extent. If the extent is not set and is assumed to be global, and your original image is very small compared to global extent (it is) then your very small image will probably not show up in the re-projection due to the resolution being too coarse. By setting the extent first you get a re-projection that has good resolution over the area of your image. Here is the result of your script with `imshow()` moved after `set_extent()`:

![imshow](https://cloud.githubusercontent.com/assets/390602/8566078/57b5bede-2553-11e5-949e-d97b4f068aa8.png)

**Comment by pelson** [comment]
Aha, thanks @ajdawson. I was sat with @kjordahl and couldn't figure it out, but you're right - cartopy had to do something to figure out the resolution of the target image.

@kjordahl - does that work for your actual image?

**Comment by kjordahl** [comment]
@pelson Yes, looks great, thanks!

![rasterio_cartopy](https://cloud.githubusercontent.com/assets/499079/8635618/e38479c4-27f0-11e5-9b8f-962d918f843f.png)

It makes sense now.
