### ISSUE TITLE
Running always_circular_stereo example crashes Python

### ISSUE THREAD

**Issue by tkanmae** [SciTools/cartopy#651]
Running always_circular_stereo example crashes Python with the following error message:

```
Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3612.
```

I'm using cartpy (0.13.0) with Python 3.4.3 on Mac OS X 10.10.4.

**Comment by pelson** [comment]
This is a problem with a badly compiled shapely (normally picking up GEOS from a homebrew installation). If you are using conda, consider installing shapely from the ioos or scitools channels (both patch shapely to fix the problem). The underlying issue is reported in https://github.com/Toblerity/Shapely/issues/177.

HTH

**Comment by tkanmae** [comment]
Thanks much!

**Comment by pelson** [comment]
My pleasure. Glad I could help.
