### ISSUE TITLE
conda install package version problem

### ISSUE THREAD

**Issue by jsboyle** [SciTools/cartopy#661]
when I run the conda install:
conda install -c scitools cartopy

It wants to downgrade my versions of numpy, scipy and matplotlib. Since these are my core packages
I am reluctant to downgrade.
Yet the cartopy documentation states that it can be installed if versions later that the ones cited.
For example I have scipy 0.15.1 and the page says it requires 0.10 or later.
The conda install wants to use 0.14.0
I assume that cartopy was verified against scipy 0.14.0
But this feature is stopping me from using cartopy. I do not have much enthusiasm for installing from source.

**Comment by darribas** [comment]
Is this also possibly related to #660?

**Comment by ocefpaf** [comment]
@jsboyle can you try `conda install -c ioos cartopy`?  The scitools channel is compiled against an old NumPy to satisfy `cfchecker` requirements.  In the IOOS channel we ignore that because we do not use `cfchecker`.

@darribas You problem is unrelated to that.  Maybe you have another `geos` installed.  Can you make sure you got `geos` from the scitools channel as well?  What is the output of `conda list | grep geos`?

**Comment by darribas** [comment]
@ocefpaf Thank you very much, taking answer to the issue not to mix up threads

**Comment by pelson** [comment]
New tooling should mean that this has now been solved with the official scitools channel. Please let us know if there are any issues with that channel.

Thanks!
