### ISSUE TITLE
Cartopy-0.13.0.tar.gz in pypi includes cython output

### ISSUE THREAD

**Issue by jpli** [SciTools/cartopy#662]
Cython output files "lib/cartopy/_crs.c" and "lib/cartopy/trace.cpp" are found in [source package in pypi](https://pypi.python.org/packages/source/C/Cartopy/Cartopy-0.13.0.tar.gz#md5=b3fc82e85132cfd1cdfacd1169b2ca4e) which I believe should not be included in the source. "lib/cartopy/_crs.c" might be generated before [commit 608f2b8ee562fe508c7894cfeaa2a324123a92e0](https://github.com/SciTools/cartopy/commit/608f2b8ee562fe508c7894cfeaa2a324123a92e0) were introduced since it causes
`test_transform_points_xyz` in "lib/cartopy/tests/test_crs.py" to fail:

```
FAIL: test_transform_points_xyz (cartopy.tests.test_crs.TestCRS)
...
(mismatch 100.0%)
 x: array([ 289231.325927])
 y: array([ 5048.038937])
```

A closer look at the pip install process (`pip install -v -v -v --upgrade --force-reinstall --no-deps --no-binary ':all:' cartopy`) shows that the two cython extensions are not generated:

```
skipping 'lib/cartopy/trace.cpp' Cython extension (up-to-date)
skipping 'lib/cartopy/_crs.c' Cython extension (up-to-date)
```

The problem can be worked arounded by recompiling the source manually:

```
pip uninstall cartopy
cd Cartopy-0.13.0/
python setup.py bdist_wheel
wheel install dist/Cartopy-0.13.0-cp27-none-linux_x86_64.whl
```

**Comment by pelson** [comment]
Hi @jpli, thanks for the report.

> which I believe should not be included in the source

These are the compiled cython files, and are effectively redundant unless you want to build without having cython installed (which is not an option with cartopy due to https://github.com/SciTools/cartopy/blob/master/setup.py#L41), so effectively I agree - these files shouldn't be in the release.

You can see I had to do some fiddling to build a source tarball in the first place (see #638), but nowhere did I include the c or cpp in the Manifest. Do you have any experience with distributing cython extensions? If so, do you have any advice?

Thanks!

**Comment by jpli** [comment]
Hi @pelson, it is the test failure that lead me to discover the issue, I don't know how to fix the code since I'm quite new to Python and Cartopy.

It seems to me that "lib/cartopy/_crs.c" is out-dated, otherwise the test would pass, it might be produced by a build process before `git checkout`, if this is the cause of the problem, the command `git ls-files -o --exclude-standard | xargs -I'{}' rm '{}'` might help.

**Comment by pelson** [comment]
We have new tarballs on pypi that should not exhibit this issue.

Thanks for the report @jpli.
