### ISSUE TITLE
Natural Earth Bathymetry does not work

### ISSUE THREAD

**Issue by eigenblutwurst** [SciTools/cartopy#688]
Dear all.

I just wanted to plot a map of bathymetry by using the Natural earth feature.
First of all the automatic download does not work by using 

    bathy = NaturalEarthFeature(category='physical',name='Bathymetry',scale='10m')

it gives again this http404error, but this is logic as a file:
http://naciscdn.org/naturalearth/10m/physical/ne_10m_Bathymetry.zip
does not exist on the server. This can be tricked by putting:

    bathy = NaturalEarthFeature(category='physical',name='Bathymetry_all',scale='10m')

and it will download the file:
Downloading: http://naciscdn.org/naturalearth/10m/physical/ne_10m_Bathymetry_all.zip

However then the shape reader expects contents of the form:
"There is no item named 'ne_10m_Bathymetry_all.shp' in the archive"

But the actual content of the file consists of: a lot of files
ne_10m_bathymetry_A_10000.dbf
ne_10m_bathymetry_A_10000.shp
ne_10m_bathymetry_A_10000.proj
ne_10m_bathymetry_A_10000.shx
ne_10m_bathymetry_B_9000.dbf
ne_10m_bathymetry_B_9000.shp
ne_10m_bathymetry_B_9000.proj
ne_10m_bathymetry_B_9000.shx
ne_10m_bathymetry_C_8000.dbf and so on

How could this be solved? By merging all the files into:
ne_10m_Bathymetry_all.dbf
ne_10m_Bathymetry_all.shp
ne_10m_Bathymetry_all.proj
ne_10m_Bathymetry_all.shx ???

Does anyone have an idea how to do this? Unfortunately, I have no idea how to do this and if this would be a proper way of doing it?

Best regards!
Hannes

P.S.> Cartopy is a great package!!! A big thanks for all the developers!

**Comment by QuLogic** [comment]
What do the numbers mean? Is it something like depth? Do you know if NE has some documentation describing the layout?

**Comment by eigenblutwurst** [comment]
Exactly the numbers mean depth in meters. No there is no documentation. Just if you directly check the website you see all these files that you can download seperately- for each depth. The _all file simply contains all these files together.

**Comment by pelson** [comment]
Details of the Natural Earth bathymetry are available at http://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-bathymetry/.

In order to get cartopy to use these, it is not possible to use the "all" link (unless you just use the shapefile functionality, rather than the Natural Earth functionality). So we need to reverse engineer the links. For instance, for 6000m level (http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_bathymetry_E_6000.zip) we should use a name of "bathymetry_E_6000". I've not understood what the letters represent (I'm sure there is a good reason for them), but the letter does change at each level. I've put together a gist which visualises the data: http://nbviewer.ipython.org/gist/pelson/626b15ffc411a359381e.

Note however, I could not get a reasonable rendering time for anything other than levels 6000 and below. The levels above are shapefiles of around 3MB and seem to be choking the drawing pipeline. I have a strong suspicion that using Fiona for shapefile reading would make those levels usable (see https://github.com/SciTools/cartopy/issues/250#issuecomment-56136368 for an option).

**Comment by philippemiron** [comment]
Hi all,

I'm trying to plot bathymetry contour line and running into some issues. Depending on the selected region, I get straight lines that looks like artifacts resulting from the combination of multiple shape file.

You can see in this simple [example](https://gist.github.com/philippemiron/57307a79a29be3ba6c19b8fc5ad0626d).

Anyone has an idea how to fix this ?
