### ISSUE TITLE
Import error: trace.so

### ISSUE THREAD

**Issue by Yefee** [SciTools/cartopy#766]
Hi, 
When I import cartopy, it returns me the error
`dlopen(/Users/Yefee/miniconda2/lib/python2.7/site-packages/cartopy/trace.so, 2): Library not loaded: @rpath/./libgeos_c.1.dylib
  Referenced from: /Users/Yefee/miniconda2/lib/python2.7/site-packages/cartopy/trace.so
  Reason: Incompatible library version: trace.so requires version 10.0.0 or later, but libgeos_c.dylib provides version 9.0.0`

I refer to the issue #660 , reinstall it using conda, finally I can import it with success. However, the trick thing is when I use it next time, it returns the error again.
Any suggestions?

**Comment by Yefee** [comment]
It is because the geos lib version conflicts.
Basemap depends on geos 3.3.x; but cartopy depends on 3.4.x
To avoid this issue, try `conda install -c conda-forge basemap`. 

Refrence:
https://github.com/matplotlib/basemap/issues/286

**Comment by pelson** [comment]
Thanks for providing the fix @Yefee. It is unfortunate that this isn't better represented in conda. We are attempting to improve the situation at conda-forge, and I'm glad to see that it has helped in this situation.

Please let me know if there is anything else needed here, otherwise, would you mind closing the issue.

Thanks!
