### ISSUE TITLE
Please clarify the licensing terms for the data

### ISSUE THREAD

**Issue by ghisvail** [SciTools/cartopy#804]
During a formal review of the `cartopy` package by Debian, it was pointed to me that the licensing terms for the [data](https://github.com/SciTools/cartopy/tree/master/lib/cartopy/data) was unclear or potentially problematic:
- `HadISST1_SST_update.nc` seems to fall under a [non-commercial license](http://www.metoffice.gov.uk/hadobs/hadcruh/licence_ncgl.html).
- `Miriam.A2012270.2050.2km.jpg` has no licensing information.
- `50-natural-earth-1-downsampled.png` has no licensing information.
- The `gshhs` files are distributed under "the Gnu Public License" but the specific version of the GPL is not specified.

Please consider clarifying the licensing on the items listed above.

**Comment by ghisvail** [comment]
Same comment for the image files in:
- lib/cartopy/tests/mpl/baseline_images/mpl

Which license do they fall under?

**Comment by ghisvail** [comment]
Please could anyone from the dev team confirm my assessment above? Thanks.

**Comment by ajdawson** [comment]
The HadISST data says this: http://www.metoffice.gov.uk/hadobs/hadisst/terms_and_conditions.html, which I think doesn't help...

The baseline images should be under the same license as the source code since they are generated by the developers to use for references in unit testing.

The image `50-natural-earth-1-downsampled.png` is downsampled from Natural Earth data whose conditions are stated at http://www.naturalearthdata.com/about/terms-of-use/ (public domain).

gshhs is LGPL, but their documentation doesn't state a version http://www.soest.hawaii.edu/pwessel/gshhg/. I think the same data are part of the GMT package which is already in debian.

The image `Miriam.A2012270.2050.2km.jpg` is from the Rapid Response section of the NASA LANCE data, which states it is in the public domain https://earthdata.nasa.gov/faq#ed-rapid-response-faq

**Comment by ghisvail** [comment]
From the link you provided for the HadISST data:
> The material may be downloaded to file or printer for the purposes of private study and scientific research.

This is the wording of a research-only / non-commercial license.

> gshhs is LGPL, but their documentation doesn't state a version http://www.soest.hawaii.edu/pwessel/gshhg/. I think the same data are part of the GMT package which is already in debian.

I'll have a look there. Thanks for the pointer.

Also thanks for clarifying the public domain licenses and where to find them.

**Comment by marqh** [comment]
@ghisvail is there more to do on this issue please, from your point of view?

for example, is there somewhere in the source tree that you would like the notes from @ajdawson included?

thank you

**Comment by ghisvail** [comment]
AFAIC, his notes are sufficient.

However, other people looking for copyright information may have trouble digging through past issues. So, I would suggest to add a `LICENSE` or `NOTICE` file under `lib/cartopy/data`, which would list the respective licensing terms of the data files.

**Comment by marqh** [comment]
closed by #843
