### ISSUE TITLE
Error in  Source Code compilation.

### ISSUE THREAD

**Issue by envhyf** [SciTools/cartopy#828]
I  tried `conda install cartopy`, but failed with error `Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3530.  

Then, I tried to install the cartopy from source code. I downloaded the latest version 0.14 and `python setup.py install` to compilation.  

The code stuck at the process of installing shapely

```
Installed /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cartopy-0.14.4.dev0-py2.7-macosx-10.10-x86_64.egg
Processing dependencies for Cartopy==0.14.4.dev0
Searching for shapely>=1.5.6
Reading https://pypi.python.org/simple/shapely/
Best match: Shapely 1.6b2
Downloading https://pypi.python.org/packages/45/35/8997278c9bf25514a781580b39e96f3c0c728d56a0003699caccd1960ab0/Shapely-1.6b2.tar.gz#md5=7f3508dbd91d9d630d477901a5f35758
Processing Shapely-1.6b2.tar.gz
Writing /tmp/easy_install-JXscSV/Shapely-1.6b2/setup.cfg
Running Shapely-1.6b2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-JXscSV/Shapely-1.6b2/egg-dist-tmp-xUCgUX
```

After several minutes, the process are stop automatically. But the cartopy has not been installed. 

I use Mac OS.X 10.10.3 with python 2.7. All dependencies are satisfied.

**Comment by pelson** [comment]
Are you using the conda-forge channel? If so, https://github.com/conda-forge/cartopy-feedstock is probably a better forum for asking this question.

My guess is that you have an old GEOS installed via homebrew/macports, or that you have shapely installed from pip (not conda) and that either of these methods is interfering with the shared object resolution.

I also own a mac, and have seen similar issues before. I haven't seen them for some time though, and I use the conda-forge version all of the time. This suggests this issue is probably no longer active - closing for now.
