### ISSUE TITLE
UTM Projection limits code doesn't match comments

### ISSUE THREAD

**Issue by coolum001** [SciTools/cartopy#868]
Looking at the UTM class, I noticed
```python
class UTM(Projection):
    """
    Universal Transverse Mercator projection.

    """
 ......

    @property
    def x_limits(self):
        easting = 5e5
        # allow 50% overflow
        return (0 - easting/2, 2 * easting + easting/2)

    @property
    def y_limits(self):
        northing = 1e7
        # allow 50% overflow
        return (0 - northing, 2 * northing + northing/2)
```

The y limits say 50% overflow, but northing is NOT divided by two, unlike all other margins.

Maybe unintended?

**Comment by pelson** [comment]
Thanks for raising. Not sure what the implication is, happy to take a PR if it addresses an issue.

cc @kaedonkers who recently looked into UTC in detail.

**Comment by QuLogic** [comment]
@pelson not sure you meant to close this?

**Comment by pelson** [comment]
> @pelson not sure you meant to close this?

I did. This isn't a report of a bug (even though there may be a bug in the code being referenced) because there is no actual *impact*. Does this actually affect anybody, and if so, *how*?

As pointed out, I'd be completely happy to take a PR if it fixes something for somebody without breaking existing correct behaviour. Without the knowledge of how it is affecting somebody's code though, how can we know if we have *fixed* it?

@QuLogic - in lieu of further details, are you happy to re-close this please?

**Comment by QuLogic** [comment]
Ah, I thought you might be waiting for a reply from @kaedonkers.
