### ISSUE TITLE
GeoAxes ignores facecolor kwarg, axes background always white

### ISSUE THREAD

**Issue by akrherz** [SciTools/cartopy#880]
I'd expect this code to make my axes background black, like it would do in vanilla matplotlib

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

ax = plt.axes(facecolor='k', projection=ccrs.PlateCarree())
ax.coastlines()
```
instead I need to do this
```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

ax = plt.axes(projection=ccrs.PlateCarree())
ax.background_patch.set_facecolor('k')
ax.coastlines(color='white')
```
![test](https://cloud.githubusercontent.com/assets/210858/25921131/eced54a0-3599-11e7-88e5-37259b9b75f4.png)

Is this designed behavior? If so, is my workaround the right thing to do?  Thanks!

PS. About done with my basemap to cartopy conversion and hope to pitch in more here now. :)

**Comment by QuLogic** [comment]
Your expected behaviour seems reasonable to me; I'd guess that `background_patch` is more of an internal thing just to get everything working nicely.

**Comment by dkillick** [comment]
Hi @akrherz, many thanks for your interest in cartopy! We always welcome contributions to cartopy although due to organisational pressures I am afraid that we are often not very good at responding to interest in cartopy in a timely manner...

Nonetheless thank you for raising this issue! It does appear that the way cartopy treats the `facecolor` kwarg to the `axes` constructor leaves a little to be desired. Partly I think this is because it appears the `facecolor` kwargs is new for matplotlib 2.0, which, strictly speaking, cartopy does not yet support (but see #773).

I've taken a look at how cartopy sets up its geoaxes instance. It appears that, as @QuLogic suggested, the `background_patch` is a sort of internal convenience used to ensure the background works with the often non-rectangular plots that cartopy can draw. However, the `background_patch` is then [explicitly published as an attribute](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L1268-L1270) so that it can be user-modified, just as you've done. It is also worth noting that the matplotlib background is hidden by cartopy - see [this code comment](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L1184-L1185).

I wonder if it wouldn't be too hard to improve this situation, at least a little bit. I'll see what I can do.

**Comment by pelson** [comment]
At the very least, I'd like to improve the documentation on this. It would also make sense to mirror the attributes between the two objects, but that would certainly be a lot harder to get right (e.g. ensuring synchronisation).

**Comment by QuLogic** [comment]
`ax.background_patch` was deprecated and replaced with normal Matplotlib methods in #1422.
