### ISSUE TITLE
Projected line does not follow transform

### ISSUE THREAD

**Issue by josephhardinee** [SciTools/cartopy#912]
I'm trying to follow the examples given and plot a line across a map in a projection. I do this in two ways. 
First we use plt.plot and a transform with many points along a line to plot out a constant latitude line.  Second we do this in one step. The two plots are giving me a projected line for the first option, but a straight (non great circle) line for the second. Is this intended or am I making a mistake? Both are using the same transform in the plot step. 

```
import numpy as np
import cartopy
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER

import matplotlib.pyplot as plt

fig = plt.figure(figsize=[10,8], dpi=100)
ax = plt.axes(projection=ccrs.LambertConformal(central_longitude=-96.0, central_latitude=39.0))

ax.set_extent([-120, -70, 22, 50])


ax.add_feature(cartopy.feature.LAND)
ax.add_feature(cartopy.feature.OCEAN)
ax.add_feature(cartopy.feature.LAKES)
ax.add_feature(cartopy.feature.BORDERS)

ax.coastlines(resolution='50m')

# Add state lines
states_provinces = cfeature.NaturalEarthFeature(
    category='cultural',
    name='admin_1_states_provinces_lines',    
    scale='50m',
    facecolor='none')
ax.add_feature(states_provinces, edgecolor='dimgray')

x1 = np.arange(-105,-79,1)
y1 = np.repeat(30,len(x1))
y2 = np.arange(30,50,1)
x2 = np.repeat(-80,len(y2))
y3 = np.repeat(49,len(x1))
x4 = np.repeat(-105,len(y2))
plt.plot(x1, y1, color='b', transform=ccrs.Geodetic())
plt.plot(x2, y2, color='b', transform=ccrs.Geodetic())
plt.plot(x1, y3, color='b', transform=ccrs.Geodetic())
plt.plot(x4, y2, color='b', transform=ccrs.Geodetic())

plt.plot([-105,-80], [30,30], 'r:', transform=ccrs.Geodetic())

```

**Comment by LukeC92** [comment]
Hi Joseph

Your 2 lines do not line up because you are using the Geodetic transformation. The Geodetic coordinate system is a truly spherical coordinate system, where a line between two points is defined as the shortest path between those points on the globe rather than 2d Cartesian space. Therefore a Geodetic line will naturally curve above or below a line of constant latitude. Your line that uses many plots shows a line of constant latitude while our other line simply uses Geodetic distance. The example at the bottom of [this page](http://scitools.org.uk/cartopy/docs/v0.15/matplotlib/intro.html) illustrates this concept quite well.

If you want to see this phenomenon in your own code you could compare how your figure looks when you change 
`ax = plt.axes(projection=ccrs.LambertConformal(central_longitude=-96.0, central_latitude=39.0))`
to
`ax = plt.axes(projection=ccrs.PlateCarree())`

**Comment by pelson** [comment]
Thanks for the great question @josephhardinee, and the equally good answer @LukeC92.

The solution to getting comparable geometries is to change

```
plt.plot([-105,-80], [30,30], 'r:', transform=ccrs.Geodetic())
```

to

```
plt.plot([-105,-80], [30,30], 'r:', transform=ccrs.PlateCarree())
```
