### ISSUE TITLE
Running tools/download.py with conda version of cartopy

### ISSUE THREAD

**Issue by jbusecke** [SciTools/cartopy#934]
I would like to download all the 'standard' shapefiles to local disk (to avoid a loss of working time due to something like #933).

I installed cartopy using conda, and it seems that tools/download.py is not included (version:`cartopy                   0.15.1                   py36_4    conda-forge`).

Is there a suggested workaround? Or do I have to install from source?

**Comment by ajdawson** [comment]
The `feature_download.py` script (it used to be called `download.py`) isn't really part of the library, which is why conda doesn't install it. Installing cartopy from source will also not install this tool.

The good news is it is a stand-alone script with a dependency on cartopy, so you can just download from github independently and run in in your conda environment where cartopy is installed.

**Comment by pelson** [comment]
I'm completely in favour of us bringing the script into the cartopy library. ```python -m cartopy.io.download_features``` or some-other such name would be good with me.

**Comment by QuLogic** [comment]
The script is now installed when you install Cartopy, as of #1602.

Additionally, if you are using conda, the [cartopy_offlinedata package](https://github.com/conda-forge/cartopy_offlinedata-feedstock) can be used to download things as a package.
